### ISSUE TITLE
Use Glossarist gem to extract all EXPRESS terms and definitions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#111]
For @hassanakbar

**Comment by ronaldtse** [comment]
Is this done in #113 ?

**Comment by HassanAkbar** [comment]
@ronaldtse I'm not sure what you mean by `use glossarist gem to read all data`. Currently we are using `expressir` gem to `read` the data and `glossarist` gem for `storing` and `writing` data.

The current workflow for generating `yaml` files is
- We read from the annotated express files using `expressir` gem
- Convert the data into `glossarist` concepts
- Write the concepts to `yaml` files

**Comment by ronaldtse** [comment]
> Currently we are using expressir gem to read the data and glossarist gem for storing and writing data

Yes this is correct:
* Previously after we extract information with the expressir gem, we create AsciiDoc (`.adoc`) files for Metanorma.
* Now we want to extract information with expressir and then create a Glossarist::ConceptSet (with Glossarist::Concept objects that are written into YAML)). Metanorma will then use metanorma-plugin-glossarist to read the files for iso-10303-2.

**Comment by HassanAkbar** [comment]
@ronaldtse We are now creating the `glossarist yaml` files.

So, is this complete or is there something else that needs to be done in the context of this ticket?

**Comment by ronaldtse** [comment]
This is all complete now. Thanks @HassanAkbar !
