### ISSUE TITLE
Convert to use Glossarist gem and models

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#113]
We should use the Glossarist gem and classes instead of plain text.

https://github.com/metanorma/stepmod-utils/blob/ccfa5e9dd0bc0070098fc09f2676735476881ab2/lib/stepmod/utils/converters/term.rb#L8-L44

**Comment by HassanAkbar** [comment]
@ronaldtse From what I understand `Glossarist` is a modeler gem to model data from hashes to class objects.

How do you suggest we should use `Glossarist` here?

**Comment by ronaldtse** [comment]
Correct. The way to use the Glossarist gem is:
1. Fit content into the Glossarist models (eg. `Concept.new`)
2. Write converters to serialize Glossarist models to Metanorma AsciiDoc. (`Concept.new.to_adoc`)

**Comment by HassanAkbar** [comment]
@ronaldtse 
> We should use the Glossarist gem and classes instead of plain text.

Can you elaborate on the `plain text`? I didn't find any plain strings in the mentioned file. 

What I understand is:
- Move the conversion logic to `Glossarist::Term`
- Inherit the `Term` class from `Glossarist::Term`

But if we go with this approach then we have to use the `reverse_adoc` gem in `Glossarist` gem. Am I getting this right?

**Comment by ronaldtse** [comment]
@HassanAkbar for example,

```rb
     "=== #{treat_acronym(term_def)}\n\n#{converted_alt}" 
```

Is a string that uses string formatting. There are numerous issues with a non-model based approach. For example, this is a possible outcome:
```
=== \n\n
```

Use a model-based approach (i.e. treating `term_def` as an object) allows us to easily prevent that from happening.

> But if we go with this approach then we have to use the reverse_adoc gem in Glossarist gem. Am I getting this right?

This is a good question. Technically, we want to do this:

1. STEPmod custom XML format => Glossarist model
2. Glossarist model to Metanorma AsciiDoc

* The code for 1 is stored in this very repo (stepmod-utils).
* Whether the code for 2 should go to Glossarist gem or `reverse_adoc` gem, or to this gem is debatable.

Thoughts?

**Comment by HassanAkbar** [comment]
@ronaldtse 

1. Agreed.
2. I think that for now:
    - The code should stay in this gem. 
    - We should just create a `Glossarist::Term` model
    - Move the validations and properties to the `Glossarist::Term` model.
    - Convert it to `Metanorma AsciiDoc` here in this gem.

Let me know if you think otherwise.

**Comment by ronaldtse** [comment]
@HassanAkbar agree. For "Convert it to Metanorma AsciiDoc here in this gem", you could also "inherit" from the `Glossarist::Term` model to do so.
