### ISSUE TITLE
Update implementation to meet agreed requirements in 2022-06-23 meeting

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#123]
This is new functionality. We will need to re-build the terms and definitions using a combination of XML and EXPRESS code.

1. We only keep ENTITY definitions in ISO 10303-2. Remove the TYPE, FUNCTION, RULE, constant definitions/descriptions from the document. This information is only provided in the EXPRESS code. 

2. As every Clause 4/5 term entry has a source, remove the NOTE, and add the “incompletely defined in this document” sentence to Clause 4 and 5 at the top.

3. Alter definition format to use a generated sentence directly from EXPRESS, keep `descriptions.xml` text (the current text we have) as a Note to entry of the term.

In order to achieve this, we have to do this.
Today, we only have the left flow. We need to add the right flow using Expressir.

<img width="944" alt="Screenshot 2022-06-30 at 7 47 34 PM" src="https://user-images.githubusercontent.com/11865/176659014-b9045909-464d-4948-9530-e4390642e83c.png">

This is what we need to do:
<img width="804" alt="Screen Shot 2022-08-09 at 12 49 45 AM" src="https://user-images.githubusercontent.com/11865/183470835-794e94d1-2cad-4d6a-bd14-e28417aac70e.png">

## Resulting structure of a term

* the "term name" is the entity name, which comes from the `{schema-name}/{schema-name}.exp` file
* the "definition" is generated from EXPRESS information of that entity from the `{schema-name}/{schema-name}.exp` file (schema name => domain, entity type => description...)
* the "Note 1" is generated from a lookup of the entity name in the currently parsed database of `{schema-name}/descriptions.xml`

## Flow

Sample code:
```sh
$ gem install expressir
$ irb
> require ‘expressir'
> require ‘expressir/express/parser'
> exp_file = ‘my-file-name.exp'
> repo = Expressir::Express::Parser.from_file(exp_file)
```

This is only for the "Clause 4 and 5 terms", i.e. the files that get generated are the `04x-*.adoc` and `05x-*.adoc` files.

What this means:
1. For all data in a chosen directory, read all the `*.exp` files. This is achieved by using the `Expressir::Express::Repo` class (something like that), it will provide you with an object (the parse tree) that contains all the EXPRESS schemas of a given directory.
2. For every `ENTITY` object in the loaded schemas, generate this output (which is built using information from `{schema-name}/{schema-name}.exp` instead of the current definition (which is sourced from `{schema-name}/descriptions.xml`. Move the current definition into a `NOTE:` block.

## Types of output

There are 3 kinds of ENTITY input with different outputs:
1. Single SUBTYPE
2. Multiple SUBTYPEs
3. No SUBTYPE

For the `{"resource" or "module"}` value:
* if the file path is `resources/*/{schema-name}.exp`, it is a "resource"
* If the file path is `modules/*/{schema-name}.exp`, it is a "module"

### Single SUBTYPE

EXPRESS:
```
ENTITY geometric_representation_context
  SUBTYPE OF (representation_context);
  coordinate_space_dimension : dimension_count;
END_ENTITY;
```

Output: (adoc, the curly braces indicate variables)
```adoc
=== {ENTITY NAME}
domain:[{"resource" or "module"}: {SCHEMA NAME}]

entity data type that is a type of {SUBTYPE} that represents a/an {ENTITY NAME} entity

NOTE: {ORIGINAL DEFINITION}
```

Example:
```adoc
=== geometric_representation_context
domain:[resource: product_definition_schema]

entity data type that is a type of representation_context that represents a geometric_representation_context entity

NOTE: A geometric_representation_context is a type of representation_context in which geometric_representation_item s are geometrically founded.
```

### Multiple SUBTYPEs

EXPRESS:
```
ENTITY characterized_product
    SUBTYPE OF (characterized_object, product);
END_ENTITY;
```

Output: (adoc, the curly braces indicate variables)
```adoc
=== {ENTITY NAME}
domain:[{"resource" or "module"}: {SCHEMA NAME}]

entity data type that is a type of {SUBTYPE 1} and {SUBTYPE 2...} that represents a/an {ENTITY NAME} entity

NOTE: {ORIGINAL DEFINITION}
```

Example:
```adoc
=== characterized_product
domain:[resource: product_definition_schema]

entity data type that is a type of characterized_object and product that represents a characterized_product entity

NOTE: A characterized_product is a type of characterized_object and a type of product for the purpose of characterizing a product.
```

### No SUBTYPE

EXPRESS:
```
ENTITY product
  ...
END_ENTITY;
```

Output: (adoc, the curly braces indicate variables)
```adoc
=== {ENTITY NAME}
domain:[{"resource" or "module"}: {SCHEMA NAME}]

entity data type that represents a/an {ENTITY NAME} entity

NOTE: {ORIGINAL DEFINITION}
```

Example:
```adoc
=== product
domain:[resource: product_definition_schema]

entity data type that represents a product entity

NOTE: thing or substance produced by a natural or artificial process.
```

**Comment by TRThurman** [comment]
It is easier to process the update if the (arm|mim|<schema_name>).xml file is used instead of the raw EXPRESS source.
The xml file has an attribute that specifies the supertypes of the ENTITY which makes it trivial to process.
Note that the xml file is the control file for publication so there can be no "extra content" included using is, as the current part 2
document has some "extra content" because in some cases, incomplete cleanup was done after a name change or move because
the "extra content' does not appear in the published document.

**Comment by TRThurman** [comment]
There are a very few ENTITIES where the entity does not represent what the name says.
Example: transformation_operator.
Easiest way to handle this is to add an attribute to the entity element in the xml file.
Can ignore for now, as we will only populate this as needed.

Alternatively, we could handle this with a human process override but that seems error prone.
We can discuss at next technical meeting.

**Comment by TRThurman** [comment]
Let's not take any action yet on reworking the algorithm as there is an additional factor to consider:
ISO 10303 has domain specific term for "entity data type" based on the overall 10303 model architecture.

An entity data type in an ARM is an Application Object.
An entity data type in a MIM and in resource parts is an entity data type.

An entity data type in a domain model is a Domain Object.
...

Where does that lead?
The alternative formulation content is different then for an ARM vs others
The grammar is identical. More of the items are parameterized.

**Comment by ronaldtse** [comment]
> It is easier to process the update if the (arm|mim|<schema_name>).xml file is used instead of the raw EXPRESS source.

@TRThurman Actually it is much easier to use the EXPRESS source because we have Expressir.

> Let's not take any action yet on reworking the algorithm as there is an additional factor to consider:
> ISO 10303 has domain specific term for "entity data type" based on the overall 10303 model architecture.

As long as we have the code that generates proper output, it should be trivial to change particular strings i.e. if we want to reword.

**Comment by TRThurman** [comment]
Ok, however you want to proceed is fine with me.

**Comment by TRThurman** [comment]
@RonTse I will be on vacation that day and would prefer to wait for a demo until the following Thursday (2022-08-18).

**Comment by ronaldtse** [comment]
Thanks @TRThurman
