### ISSUE TITLE
Annotated EXPRESS: inline NOTEs/examples/figures/tables from resource.xml

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#143]
For the generation Annotated EXPRESS, we have an issue (beyond the fixed #138) because the schemas (e.g. `action_schema`) contain inline notes, examples, figures and tables.

It is unclear how we should extract those, because those are context dependent (e.g. within a list item, there is a NOTE). If we pull out the NOTE, it no longer makes sense.

_Originally posted by @ronaldtse in https://github.com/metanorma/stepmod-utils/issues/138#issuecomment-1247837463_

**Comment by TRThurman** [comment]
Is this still an issue?

**Comment by ronaldtse** [comment]
On the TF 1 Sept 1 call it is decided that Annotated EXPRESS will support Metanorma AsciiDoc syntax within the remarks, so this is no longer considered an issue.
