### ISSUE TITLE
Skip "Note 1 to entry" in a term where the first sentence just says "A[n] ... is a type of <<express...>>."

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#155]
From: https://github.com/metanorma/iso-10303-2/issues/135

In ISO 10303-2 all entities are given a "Note 1 to entry" that is extracted from the first sentence of the EXPRESS annotation.

However, for some entities, the first sentence is just "A[n] ... is a type of <<express...>>.", which does not give more information than the generated definition:

<img width="823" alt="Screenshot 2023-03-30 at 10 24 33 AM" src="https://user-images.githubusercontent.com/11865/228711963-735714cf-fb80-48e8-9d36-4edc41b2f6df.png">

In this case, the "Note 1 to entry" is redundant and should be skipped.

When we see the pattern "A[n] ... is a type of <<express...>>.", we skip the generation of "Note 1 to entry".

```sh
gg 'A.* is a type of <<express[^>]*>>\.'
```

For example:

```
data/modules/model_parameter/arm_annotated.exp:A **Test_method_based_parameter_assignment** is a type of <<express:Model_parameter_arm.Parameter_assignment,Parameter_assignment>>.
```

The "Note 1 to entry" should be skipped for the `Test_method_based_parameter_assignment` entity.

**Comment by HassanAkbar** [comment]
@ronaldtse Do we only need to do this for `yaml` concepts only or for `adoc` as well?
