### ISSUE TITLE
Exclude `iso13584_expressions_schema` from stepmod-utils extraction of terms despite being in repository_index.xml

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#157]
From https://github.com/metanorma/iso-10303-2/issues/138

**Comment by HassanAkbar** [comment]
@ronaldtse Do we need to add an option to skip a concept or can we hardcode this value in `stepped-utils`?

**Comment by ronaldtse** [comment]
@HassanAkbar we can hardcode this in stepmod-utils.
