### ISSUE TITLE
Create single command that migrates STEPmod repository into SRL

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#160]
Given the STEPMod directory (`stepmod/`), produce the following:

2 commands:
* `stepmod-srl-migrate-docs --stepmod-data-dir stepmod/data --srl-docs-dir documents`
* `stepmod-srl-migrate-schemas --stepmod-data-dir stepmod/data --srl-schemas-dir schemas`

## Resulting output

* `documents/`: containing:
    * `documents/resources/{document-name}` and `documents/modules/{document-name}`:
        * `stepmod2mn` document migration output (Metanorma `*.adoc` files)
* `schemas/`: containing:
    * `schemas/{schema-name}/`
        * `stepmod2mn` migrated EXPRESS-G diagrams (`*.svg` files)
        * `stepmod-utils` "Annotated EXPRESS" output (`*_annotated.exp` files => renamed to `*.exp`)
        * `stepmod-utils` "EXPRESS schema changes" output (`*.yaml` files) (https://github.com/metanorma/stepmod-utils/issues/146)

## Create Metanorma documents: `stepmod-srl-migrate-docs`

Prerequisites:
* Make sure `stepmod2mn.jar` is available, if not, download it.

Steps:
* create the `srl-docs-dir` directory (i.e. `documents/`)
* run `stepmod2mn.jar` to migrate documents into the `srl-docs-dir` directory

## Migrate EXPRESS schemas: `stepmod-srl-migrate-schemas`

Prerequisites:
* Make sure `stepmod2mn.jar` is available, if not, download it. 

Steps:
* create the `srl-schemas-dir` directory (i.e. `schemas/`)
* run the functionality of `stepmod-annotate-all` to create `*_annotated.exp` files (but name them `*.exp` without the `_annotated` suffix), place them in `{srl-schemas-dir}/{schema-name}/*.exp`
* run the functionality of `stepmod-extract-changes` to create `*.yaml` files for schema change information, place them in `{srl-schemas-dir}/{schema-name}/*.yaml`
* run `stepmod2mn` to migrate the EXPRESS-G files (the `*.svg` files), place them in `{srl-schemas-dir}/{schema-name}/*.svg`

## One step command: `stepmod-srl-migrate`

* Run `stepmod-srl-migrate-docs`
* Run `stepmod-srl-migrate-schemas`

**Comment by ronaldtse** [comment]
The `[stepmod-srl-migrate](https://github.com/metanorma/stepmod-utils/issues/160#diff-a91ee891f95087f53f0c7bf9d244dba8851afeae9f5a7db57793ada73c276c4e)` command is not documented. Please add it to the README ASAP.

**Comment by TRThurman** [comment]
@ronaldtse, What function transforms the mapping specs?
