### ISSUE TITLE
Broken population of resource.xml attributes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod-utils#178]
This does not impact me, but it is a bug.

In populating the resource.xml file in iso-10303-stepmod/data/resource_docs/mesh-based_computational_fluid_dynamics/resource.xml , a space is being missed in the population of `<schema>` attributes:

````
    <schema name="domain_schema" version="2" number.supersedes="5952"number="10061"></schema>
````

Don't do a new release for stepmod2mn yet though, there will be more :)

**Comment by Intelligent2013** [comment]
The source `resource.xml` isn't valid XML.
XMLSpy checking result:
![image](https://github.com/metanorma/stepmod-utils/assets/5559926/f73abddf-b7a8-40c0-960f-730b891e07f9)


`stepmod2mn` output:
```xml
Transforming...                                                                                                                                                                                                    
file:///D:/Work/Metanorma/repositories/iso-10303-stepmod/data/resource_docs/mesh-based_computational_fluid_dynamics/resource.xml; Line #64; Column #70; Element type "schema" must be followed by either attribute specifications, ">" or "/>".
[Fatal Error] :-1:-1: Premature end of file.
org.xml.sax.SAXParseException; Premature end of file.
at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
at org.metanorma.stepmod2mn.getRootElement(stepmod2mn.java:608)
at org.metanorma.stepmod2mn.convertstepmod2mn(stepmod2mn.java:429)
at org.metanorma.stepmod2mn.main(stepmod2mn.java:358)
```

I can do only one thing - manually update xml. Will do in the `iso-10303-stepmod` repository.

**Comment by TRThurman** [comment]
Please provide a list of these invalid resource.xml files.

**Comment by Intelligent2013** [comment]
> Please provide a list of these invalid resource.xml files.

@TRThurman no more invalid resource.xml files. There was only one (https://github.com/metanorma/iso-10303-stepmod/blob/main/data/resource_docs/mesh-based_computational_fluid_dynamics/resource.xml)

**Comment by TRThurman** [comment]
Entered an issue in WG12 issue tracker.
This document is not under active development.
The published document is a pdf part.
So don't wait for WG12 to take any action.

**Comment by ronaldtse** [comment]
@Intelligent2013 we can't just update the repo manually because the repository is automatically populated daily. 

Can you please provide the commit ID/diff so we can incorporate this patch in a protected SMRL branch?

**Comment by TRThurman** [comment]
Because the resource.xml is unused in the current SMRL, I will proposes a hot-fix for this.
Stay tuned.

**Comment by Intelligent2013** [comment]
> Can you please provide the commit ID/diff so we can incorporate this patch in a protected SMRL branch?

@ronaldtse commit for `data/resource_docs/mesh-based_computational_fluid_dynamics/resource.xml`:
https://github.com/metanorma/iso-10303-stepmod/commit/f89d67610d790f4ca4a082e5140dca91b3dfbe75
