### ISSUE TITLE
Copy over referenced images from resource_docs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#184]
From: https://github.com/metanorma/iso-10303-stepmod-wg12/issues/4

There are images referenced under the `resource_docs` directory, such as:
* `data/resource_docs/draughting/leader_line_shared_dimension_tolerance.gif`

During the generation of the Annotated EXPRESS, we need to also move these images into the location of where the schema is. For example, this `leader_line_shared_dimension_tolerance.gif` file belongs to `data/resources/draughting_element_schema/`,

So:
* `data/resource_docs/draughting/leader_line_shared_dimension_tolerance.gif` == Moves to  ==>
* `{schema-base-dir}/draughting_element_schema/leader_line_shared_dimension_tolerance.gif`

The full list of images are provided here:
* https://github.com/metanorma/iso-10303-stepmod-wg12/issues/4#issuecomment-1748990824

**Comment by HassanAkbar** [comment]
@ronaldtse @opoudjis Do we need to move the images or just create an alias folder & keep the original images where they are?

**Comment by ronaldtse** [comment]
@HassanAkbar we need to copy out the images, not an alias folder. Thanks!
