### ISSUE TITLE
Invalid asciidoc syntax generated in express files

### ISSUE THREAD

**Issue by HassanAkbar** [metanorma/stepmod-utils#186]
### Issue
Invalid asciidoc syntax generated in express files as explained in https://github.com/metanorma/stepmod2mn/issues/93

### Solution
Remove `**` from start and end if there is an equation tag inside the `<b>` tag

**Comment by ronaldtse** [comment]
@HassanAkbar can you please help release? Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse I've released a new version `0.3.32`

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar !
