### ISSUE TITLE
ISO 10303 ARM,MIM,IR entity and type declarations are not included in proposed 10303-2 but should be

### ISSUE THREAD

**Issue by TRThurman** [metanorma/stepmod-utils#2]
ISO 10303 defines a number of engineering domain languages but often the terms in those languages are only formally defined in the EXPRESS source in the standard.
Creating ISO 10303-2 from only clause 3 of the standard satisfies the letter of the requirement denoted in the PWI for ISO 10303-2 as well as the report out from the October workshop but does not address the underlying issue that most of the over 5,000 terms in ISO 10303 are not available on the OBP.

The logic provided for not addressing this is that the problem is too hard because resources are not available to create hiqh quality definitions for the EXPRESS declarations.

**Comment by ronaldtse** [comment]
@TRThurman do you have an example for the terms not available from Clause 3s?

Do you mean names like `aic_associative_draughting_elements`?

**Comment by TRThurman** [comment]
Yes, exactly

**Comment by ronaldtse** [comment]
Got it. There’s not even a definition of this inside the exp files. 

Is it debatable whether these are actually “terms” that should appear in the OBP, or reference items only relevant to the EXPRESS code?

In any case it is useful to have a definition for each of these names — can we reuse the text from the <schema> description?

**Comment by TRThurman** [comment]
The text from the description is what we should use to start with.
Reformatting to meet iso directives for terms will have to wait for later.

**Comment by ronaldtse** [comment]
Where would the description for `aic_associative_draughting_elements` be found?

In its `description.xml`, there is only this snippet:

```xml
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Schema: aic_associative_draughting_elements
<express_ref linkend="aic_associative_draughting_elements::aic_associative_draughting_elements"/>
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<ext_description linkend="aic_associative_draughting_elements">
	<p>
	This clause specifies the EXPRESS schema that uses elements from the integrated resources
	and contains the types, entity specializations, and functions that are specific to this part of ISO 10303.
	</p>
	<note>
		There may be subtypes and items of select lists that appear in the integrated resources that are not imported into the AIC.
		Constructs are eliminated from the subtype tree or select list through the use of the implicit interface rules of ISO 10303-11.
		References to eliminated constructs are outside the scope of the AIC.
		In some cases, all items of the select list are eliminated.
		Because AICs are intended to be implemented in the context of an application protocol, 
		the items of the select list will be defined by the scope of the application protocol.
	</note>
</ext_description>
```

But it is clearly not suited as a "description" for this name?

**Comment by TRThurman** [comment]
That is because it is a schema in which case the description of it is an html resource is in resource.xml.
I was thinking of entity function and rule. description and forgot about schemata but they are valid as well.

**Comment by TRThurman** [comment]
"aic_associative_draughting_elements
an application interpreted construct for the description of structures to associate the annotation used in draughting with the geometric aspects of the shape where the annotation applies

**Comment by ronaldtse** [comment]
@TRThurman the closest thing I can find for a description of this schema is:

data/resource_docs/associative_draughting_elements/resource.xml
```
<schema name="aic_associative_draughting_elements" version="3" number="9671" number.supersedes="8489">
<!-- Note schema EXPRESS are in ..\resources\resource_name name_of_schema.xml -->
   
   <introduction>
   		This application interpreted construct provides a consistent set of entities for the
        description of structures to associate the annotation used in draughting 
        with the geometric aspects of the shape where the annotation applies.
   </introduction>
```

This goes back to Annotated EXPRESS -- once we can parse Annotated EXPRESS and have this "schema introduction" moved in there, we could link `aic_associative_draughting_elements` to this introduction as a basis for its definition.

**Comment by TRThurman** [comment]
Sent from my iPhone

> On Jul 3, 2020, at 6:55 PM, Ronald Tse <notifications@github.com> wrote:
> 
> ﻿
> @TRThurman the closest thing I can find for a description of this schema is:
> 
> data/resource_docs/associative_draughting_elements/resource.xml
> 
> <schema name="aic_associative_draughting_elements" version="3" number="9671" number.supersedes="8489">
> 
>    
>    <introduction>
>    		This application interpreted construct provides a consistent set of entities for the
>         description of structures to associate the annotation used in draughting 
>         with the geometric aspects of the shape where the annotation applies.
>    </introduction>
Yes that is correct reference.
> This goes back to Annotated EXPRESS -- once we can parse Annotated EXPRESS and have this "schema introduction" moved in there, we could link aic_associative_draughting_elements to this introduction as a basis for its definition.
> 
I agree
