### ISSUE TITLE
expressir failure on tail comments.

### ISSUE THREAD

**Issue by TRThurman** [metanorma/stepmod-utils#216]
The tail comments in geometric_model_schema.exp on wg12-stepdev branch *-229 causes Expressir to report a false positive.

**Comment by opoudjis** [comment]
Would have been helpful for you to include the error message. I'll try to replicate it before passing it on to the right person, but you know how complicated the document generation workflow is, and how difficult it is to get it running, and I have no idea how I'm going to. 

There is a reason a ticket with no information, like this, has just been sitting here unactioned for two weeks.

**Comment by TRThurman** [comment]
I tried and failed to assign this to Ron, as we had discussions about Expressir and tail comments. The reference to geometric_model_schema should included the schema but the -229 branch is no longer available on wg12-stepdev. It is on develop in some form, but I iwll go back and find the commit when I get home. On travel, no computer.

**Comment by ronaldtse** [comment]
This issue has been resolved in:
* https://github.com/lutaml/expressir/issues/132

Closing.
