### ISSUE TITLE
unterminated pass block in ISO-10303-42

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod-utils#220]
> bundle exec asciidoctor -b iso -r metanorma-iso document.adoc --trace
> asciidoctor: WARNING: <stdin>: line 51046: unterminated pass block

This leads to an infinite loop in Metanorma.

Because of the fundamental design flaw of Lutaml not bothering to save a document to disk, I have no idea where it is, and @ronaldtse this needs to have been taken care of years ago: https://github.com/metanorma/metanorma-plugin-lutaml/issues/100

I am now in the shitty position of having to binary search through the  included schemas, to track this down. And I am once again furious that I am the only developer stuck with this task. 

@HassanAkbar Nothing for you to action until I have found this.

**Comment by opoudjis** [comment]
Until @ronaldtse ensures that https://github.com/metanorma/metanorma-plugin-lutaml/issues/100 happens, @ronaldtse can deal with the bug reports:

The issue is in schemas/resources/geometry_schema/geometry_schema.exp

If I include up to geometry_schema.degenerate_toroidal_surface.__note, the document compiles.

If I include the following note,

````
(*"geometry_schema.degenerate_toroidal_surface.__note"
See Figure <<figure_Geomfig14,(15)>> for illustration of the attributes.
*)
````

it crashes saying that the stem block is unterminated.

You will notice that there is no stem block there, so this is some sort of corruption of the Liquid template.

**Comment by opoudjis** [comment]
@HassanAkbar I note with dismay this:

````
Figure <<figure_Geomfig14,(15)>> 
````

I explicitly requested in https://github.com/metanorma/stepmod-utils/issues/194 that we get rid of all these schema-specific numbers, since they will be overridden by numbering within the document: `<<figure_Geomfig14,(15)>>` must become  `<<figure_Geomfig14>>`. Any content after the comma in cross-references of `(number)` is destroying the correct numbering of cross-references in the documents, and must be deleted.

**Comment by opoudjis** [comment]
@TRThurman If you're wondering why new issues are turning up with 42: the underlying Liquid template that generates the clauses for each schema has been expanded and updated, but that is shaking out new problems in how Liquid is putting the document together, as it is now picking up content it wasn't before.

**Comment by ronaldtse** [comment]
We never had `pass` blocks. I believe only very recently @Intelligent2013 added `pass:[...]` blocks.

Ping @Intelligent2013 .

**Comment by opoudjis** [comment]
No, ++++ in Asciidoc is a kind of pass block.

**Comment by ronaldtse** [comment]
The real problem with Part 42 is the broken fake math, and especially the amount of it. We are simply running into uncharted territory of clearing 20 years of technical debt that hasn't been addressed in any way.

**Comment by opoudjis** [comment]
What I know is that  this document was compiling last month, it isn't now, and the only thing I know has changed in between is the Liquid templates.

**Comment by Intelligent2013** [comment]
> We never had `pass` blocks. I believe only very recently @Intelligent2013 added `pass:[...]` blocks.
> 
> Ping @Intelligent2013 .

I've added a few days ago this block
```
pass-format:all[--]
```
for the 'module' documents only, but ISO-10303-42 is 'resource' document.

**Comment by opoudjis** [comment]
@HassanAkbar Found it. You are generating:

````

The sense of this normal is away from the furthest point on the circle of radius R in the plane normal to z centred at *C*.



The sense of this normal is opposite to the direction of


[stem]
++++
(∂ σ)/(∂ u) × (∂ σ)/(∂ v) .
++++See Figure <<figure_Geomfig14,(15)>> for illustration of the attributes.

````

Because the stem expression is not being terminated, an infinite loop is happening. 

Always, without fail, output a blank line IMMEDIATELY after outputting `++++`. This is of course the same issue as https://github.com/metanorma/stepmod-utils/issues/223

**Comment by opoudjis** [comment]
Yes. If you see `++++...++++`, just put a blank line after it. It's never incorrect to, since ++++...++++ is a block.

Thing is, I did put a blank line after it when debugging yesterday, and I still got a crash, but at least we can eliminate this error.

**Comment by ronaldtse** [comment]
@opoudjis we can fix this in the templates by adding a new line after each NOTE. As @HassanAkbar mentioned, the `(*...*)` is correct.

**Comment by opoudjis** [comment]
@manuelfuenmayor Fix needed in templates: all instances of NOTE need to have a blank line after them.

**Comment by manuelfuenmayor** [comment]
@opoudjis, currently, there is a blank line at both top and bottom side of every NOTE:

```liquid
{% assign notes = remark_items | where: "id", "__note" %}
{% for note in notes %}
{% if note.remarks.size > 0 %}
{% for remark_note in note.remarks %}

[NOTE]
--
{{remark_note}}
--

{% endfor %}
{% endif %}
{% endfor %}
```

I'm not getting any crashes on ISO 10303-42.

**Comment by opoudjis** [comment]
Confirmed.
