### ISSUE TITLE
Generate ancillary files needed for Metanorma

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod-utils#233]
In https://github.com/metanorma/stepmod2mn/issues/124#issuecomment-1859657292 , 10 days ago, @ronaldtse decided that the functionality in stepmod2mn to generate the files collection.sh, cover.html, html_attachments.sh, should be removed, because they were properly preprocessing activity which needs to be done by stepmod-utils instead.

With those files removed, and with no task assigned to reproduce their functionality, nobody is able to generate ISO 10303 collections.

(Yet another plate crashing to the floor.)

This task is to provide that functionality in stepmod-utils instead. @HassanAkbar please consult with @Intelligent2013 and @ronaldtse on what is involved.

**Comment by HassanAkbar** [comment]
@ronaldtse @Intelligent2013 

To summarize my discussion with @opoudjis:
- We need to remove the `collection.sh` file
- We need to generate 1 file `cover.html`  -> This will be a static file
- We need to incorporate the content of `html_attachments.sh` into stepmod-annotate-all.

Is this correct or am I missing something here?

**Comment by TRThurman** [comment]
@HassanAkbar Maybe not missing but I expect the current collection function doesn't go away until this new function is validated.

**Comment by opoudjis** [comment]
The intention here is to make this a `metanorma collection` command that can stand on its own, because all the preprocessing that is currently being doing in `collection.sh` will be done by stepmod-utils instead. And the refactoring makes sense, but...

... The current collection functionality **has already gone away**, it has been removed from the latest instance of stepmod2mn, without any arrangements being made for its replacement in stepmod-utils. This ticket is the request to do so.

When I say "(Yet another plate crashing to the floor.)", there is a reason for it.

Not generating the remaining collections until the functionality is reinstated. Yes, the change could be undone in stepmod2mn, but given how this has been proceeding, I'd rather not risk even more confusion.

**Comment by HassanAkbar** [comment]
I have a few questions related to `stepmod-annotate-all`
- I've output the `cover.html` file in the `stepmod-output-dir`, Is this correct?
- Converted the `html_attachments.sh` file to `ruby`. (Need help with this, Not sure when to call this) 
- `collection.sh` file was calling the `html_attachments.sh`, now we need to remove this so how will the `html_attachments.sh` will be called?

@ronaldtse @opoudjis Also can you let me know what the complete workflow is? Or how should I test this?

What I've done so far is 

- Ran `java -Xss5m -jar target/stepmod2mn-1.34.jar ../iso-10303-stepmod-wg12/publication/part1000/CR00001/publication_index.xml --output ./CR_00001 --input-documents ../iso-10303-srl/documents/iso-10303-1001`, It generate only 2 files but I'm not sure what to do next.

**Comment by stuartgalt** [comment]
I don't think CR_00001 has any resource parts.   I would try  .... publication/part1000/CR_Geometry_2  In theory it contains 10303-42, 10303-43, and 10303-46.  The module entries in this publication_index.xml may be ignored when generating an SRL

**Comment by HassanAkbar** [comment]
> I don't think CR_00001 has any resource parts. I would try .... publication/part1000/CR_Geometry_2 In theory it contains 10303-42, 10303-43, and 10303-46. The module entries in this publication_index.xml may be ignored when generating an SRL

Thank you @stuartgalt, I’m not sure about the complete workflow here.
But I will test this and see where it leads to. I’ll let you know if I have any questions after testing this.

**Comment by HassanAkbar** [comment]
@ronaldtse I've looked at the different repos and tried to understand the flow, but I'm still confused on what needs to be done in this ticket. 

I'm not sure about how the `collection.sh` was being run previously, was it manual or was there some script that was running it?
And now if we add this to `stepmod-utils` then will run on every schema? should we add this to the `srl-migrate` command or will this run after the schemas are generated?

**Comment by TRThurman** [comment]
@HassanAkbar @kwkwan, you need to talk!
See this ticket: https://github.com/metanorma/iso-10303-srl/pulls

The immediate task overall is to be able to build a collection based on content of publication_index.xml
As I understand it from @opoudjis, the collection was run manually.
@stuartgalt and @TRThurman are perfectly happy with letting it run manually just so we can get a collection built and move on to the collection top level presentation layout.

I hope this user-focused information is helpful.

**Comment by ronaldtse** [comment]
Done in metanorma/iso-10303-srl#30
