### ISSUE TITLE
(URGENT) ARM/MIM Longform EXPRESS Change YAML generation missing lots of data

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#235]
The following files (in [iso-10303-smrl](https://github.com/metanorma/iso-10303-smrl)) contain longform changes:

Out of over 10k lines of changes:
* https://github.com/metanorma/iso-10303-stepmod-wg12/blob/SMRLv9-part2/data/modules/ap209_multidisciplinary_analysis_and_design/module.xml#L51-L11103

The Change YAML only has less than 20.

https://github.com/metanorma/iso-10303-srl/blob/main/schemas/modules/ap209_multidisciplinary_analysis_and_design/arm_lf.changes.yaml
```yaml
---
schema: ap209_multidisciplinary_analysis_and_design
change_edition:
- version: '2'
  description: |-
    * Add SELECT value 'ENTITY Envelope'
    * Add SELECT value 'ENTITY Evidence'
    * Add SELECT value 'ENTITY Interface_connection'
    * Add SELECT value 'ENTITY Interface_connector_occurrence'
    * Add SELECT value 'ENTITY Interface_definition_connection'
    * Add SELECT value 'ENTITY Message'
    * Add SELECT value 'ENTITY Product_group'
    * Add SELECT value 'ENTITY Product_group_membership'
    * Add SELECT value 'ENTITY State'
    * Add SELECT value 'ENTITY State_assertion'
    * Add SELECT value 'ENTITY State_assessment'
    * Add SELECT value 'ENTITY State_relationship'
    * Add SELECT value 'ENTITY Validation'
    * Add SELECT value 'ENTITY Verification'
```

This task is to fix this.

To verify the content please check the following files (in [iso-10303-stepmod-wg12](https://github.com/metanorma/iso-10303-stepmod-wg12)) that describe longform changes:

```
data/modules/ap209_multidisciplinary_analysis_and_design/sys/g_change.htm:      <h2><a name="arm_longform.changes2">F.2.4 Changes made to the ARM Longform</a></h2>
data/modules/ap210_electronic_assembly_interconnect_and_packaging_design/sys/g_change.htm:      <h2><a name="arm_longform.changes4">F.4.4 Changes made to the ARM Longform</a></h2>
data/modules/ap210_electronic_assembly_interconnect_and_packaging_design/sys/g_change.htm:      <h2><a name="arm_longform.changes5">F.5.4 Changes made to the ARM Longform</a></h2>
data/modules/ap210_electronic_assembly_interconnect_and_packaging_design/sys/g_change.htm:      <h2><a name="arm_longform.changes6">F.6.3 Changes made to the ARM Longform</a></h2>
data/modules/ap242_managed_model_based_3d_engineering/sys/g_change.htm:      <h2><a name="arm_longform.changes2">F.2.5 Changes made to the ARM Longform</a></h2>
data/modules/ap242_managed_model_based_3d_engineering/sys/g_change.htm:      <h2><a name="arm_longform.changes3">F.3.4 Changes made to the ARM Longform</a></h2>
data/modules/ap242_managed_model_based_3d_engineering/sys/g_change.htm:      <h2><a name="arm_longform.changes4">F.4.4 Changes made to the ARM Longform</a></h2>
data/modules/elemental_topology/sys/g_change.htm:      <h2><a name="arm_longform.changes6">F.6.2 Changes made to the ARM Longform</a></h2>


data/modules/ap209_multidisciplinary_analysis_and_design/sys/g_change.htm:      <h2><a name="mim_longform.changes2">F.2.5 Changes made to the MIM Longform</a></h2>
data/modules/ap210_electronic_assembly_interconnect_and_packaging_design/sys/g_change.htm:      <h2><a name="mim_longform.changes4">F.4.5 Changes made to the MIM Longform</a></h2>
data/modules/ap210_electronic_assembly_interconnect_and_packaging_design/sys/g_change.htm:      <h2><a name="mim_longform.changes5">F.5.5 Changes made to the MIM Longform</a></h2>
data/modules/ap210_electronic_assembly_interconnect_and_packaging_design/sys/g_change.htm:      <h2><a name="mim_longform.changes6">F.6.4 Changes made to the MIM Longform</a></h2>
data/modules/ap242_managed_model_based_3d_engineering/sys/g_change.htm:      <h2><a name="mim_longform.changes2">F.2.6 Changes made to the MIM Longform</a></h2>
data/modules/ap242_managed_model_based_3d_engineering/sys/g_change.htm:      <h2><a name="mim_longform.changes3">F.3.5 Changes made to the MIM Longform</a></h2>
data/modules/ap242_managed_model_based_3d_engineering/sys/g_change.htm:      <h2><a name="mim_longform.changes4">F.4.5 Changes made to the MIM Longform</a></h2>
```

_Originally posted by @ronaldtse in https://github.com/metanorma/stepmod-utils/issues/210#issuecomment-1878393080_

**Comment by HassanAkbar** [comment]
@ronaldtse Currently the `longform_changes` file is generated as discussed in this ticket -> [#146](https://github.com/metanorma/stepmod-utils/issues/146).

The issue is that `arm.additions` are outside the `arm.changes` tag that is in [ap209_multidisciplinary_analysis_and_design/module.xml](https://github.com/metanorma/iso-10303-stepmod-wg12/blob/4149f963f7f5a68a5413a13c9e46edf2a31b733c/data/modules/ap209_multidisciplinary_analysis_and_design/module.xml#L78).

Should we update the structure of the XML file or do we need to update our code to handle this structure ?
If we need to update our code then can you let me know which structure should be followed here ?

**Comment by TRThurman** [comment]
@HassanAkbar, Please update the structure. I will ask the Convener for permission to fix this on the develop branch.

**Comment by TRThurman** [comment]
> @ronaldtse Currently the `longform_changes` file is generated as discussed in this ticket -> [#146](https://github.com/metanorma/stepmod-utils/issues/146).
> 
> The issue is that `arm.additions` are outside the `arm.changes` tag that is in [ap209_multidisciplinary_analysis_and_design/module.xml](https://github.com/metanorma/iso-10303-stepmod-wg12/blob/4149f963f7f5a68a5413a13c9e46edf2a31b733c/data/modules/ap209_multidisciplinary_analysis_and_design/module.xml#L78).
> 
> Should we update the structure of the XML file or do we need to update our code to handle this structure ? If we need to update our code then can you let me know which structure should be followed here ?

@HassanAkbar I am somewhat surprised at this issue. I assumed you were using an xml founded parser that knew xpath. The question should never have occurred, but I am operating on incomplete knowledge of course.

**Comment by ronaldtse** [comment]
> The issue is that `arm.additions` are outside the `arm.changes` tag that is in [ap209_multidisciplinary_analysis_and_design/module.xml](https://github.com/metanorma/iso-10303-stepmod-wg12/blob/4149f963f7f5a68a5413a13c9e46edf2a31b733c/data/modules/ap209_multidisciplinary_analysis_and_design/module.xml#L78).

Correct. The `<arm.additions>` (and `<mim.additions>`) tag is under [`<arm_longform.changes>`](https://github.com/metanorma/iso-10303-stepmod-wg12/blob/4149f963f7f5a68a5413a13c9e46edf2a31b733c/data/modules/ap209_multidisciplinary_analysis_and_design/module.xml#L70) (and [`<mim_longform.changes>`](https://github.com/metanorma/iso-10303-stepmod-wg12/blob/4149f963f7f5a68a5413a13c9e46edf2a31b733c/data/modules/ap209_multidisciplinary_analysis_and_design/module.xml#L6323) which is not expected by #146.

Could you help extend our code to generate:
* `<arm_longform.changes>` into `arm_lf.changes.yaml` (to match the filename of `arm_lf.exp`)
* `<mim_longform.changes>` into `mim_lf.changes.yaml` (to match the filename of `mim_lf.exp`)

The structure of the `<*.changes>` should be identical across types (`arm`, `mim`, `arm_longform` and `mim_longform`).

Thanks.

**Comment by ronaldtse** [comment]
> I assumed you were using an xml founded parser that knew xpath.

In the original specification of #146, I did not consider the possibility that something like `<arm_longform.changes>` existed but just `<arm.changes>`. Another reason why it is finally a relief for everyone to migrate the structure away for the SRL.

**Comment by TRThurman** [comment]
I am sorry but there is no excuse to ignore the dtd.The dtd for an xml file is listed in the header of that xml file! Read it.I almost fired off a bug report that would make us look silly but decided to see if the file was valid and it was.I don’t look forward to interpreting error messages from the metanoma build environment.On Jan 5, 2024, at 5:54 PM, Ronald Tse ***@***.***> wrote:﻿

I assumed you were using an xml founded parser that knew xpath.

In the original specification of #146, I did not consider the possibility that something like <arm_longform.changes> existed but just <arm.changes>. Another reason why it is finally a relief for everyone to migrate the structure away for the SRL.

**Comment by ronaldtse** [comment]
@TRThurman can you point out which particular DTD are you referring to that mentions `arm_longform.changes`?
