### ISSUE TITLE
Drop testing Ruby `2.7` since it won't work anymore

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#245]
From @hassanakbar:

> @ronaldtse as shale depends on ruby `3.0`, if we want to use it then we will have to drop support for ruby `2.7` from `stepmod-utils`.

Ruby 2.7 is failing as the gem no longer supports it. 

We need to update the tests so it no longer tests against 2.7 if not supported. Ping @CAMOBAP .

_Originally posted by @ronaldtse in https://github.com/metanorma/stepmod-utils/issues/240#issuecomment-2065569776_

**Comment by CAMOBAP** [comment]
2.7 removed from all repos and 3.3 added as experimental
