### ISSUE TITLE
Changes YAML missing `changes/change/arm.changes/description` element

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#257]
From https://github.com/metanorma/iso-10303-srl/issues/209#issuecomment-2095101572

From Part 1064:

`data/modules/event/module.xml`:
```xml
	<changes>
		<change version="2">
			<arm.changes>
				<description>ARM EXPRESS-G Diagrams have been updated</description>
			</arm.changes>
		<mapping.changes>
			<mapping.change>Event entity mapping updated.</mapping.change>
		</mapping.changes>
		</change>
	</changes>
```

This description does exist, but the "changes YAML" code isn't migrating this sentence properly.

Resulting Changes YAML:

`schemas/modules/event/arm.changes.yaml`:
```yaml
---
schema: event
change_edition:
- version: '2'
```
@HassanAkbar can you please help? Thanks.

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-10303-srl/issues/209#issuecomment-2095101572_

**Comment by HassanAkbar** [comment]
@ronaldtse I'm looking into it.
