### ISSUE TITLE
hard-coded data directory in stepmod-extract-terms utility

### ISSUE THREAD

**Issue by TRThurman** [metanorma/stepmod-utils#26]
The stepmod-extract-terms utility assumes a hard-coded directory name in the path to the 'data' directory:
In practice the directory name above data is always 'stepmod' and then whatever local name the user picks.

```
This
>pwd
/Users/tom/boost-workspace/stepmod
>stepmod-extract-terms {data}
results in:
Searching for ../iso-10303-stepmod/data/{resource,module,application_protocol,business_object_model}.xml....
```

Correct behaviour is to use the current directory or an explicitly provided path based on usual unix syntax.

**Comment by ronaldtse** [comment]
@TRThurman sorry I forgot to remove the debugging path -- it should now work as expected!
