### ISSUE TITLE
Update all instances of express_ref:[]

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod-utils#36]
Follow on from https://github.com/metanorma/metanorma/issues/122

Currently `express_ref:[A]` is used to generate cross-references between documents. We no longer use `express_ref:[]`, and all instances of it need to be updated to the new indirect cross-reference format implemented there.

Each cross reference passed to express_ref is of form `schema ("." (prefix ".")* label)?`, where each of schema, prefix, label is a string that does not contain ".". So "action_schema.functions.type1" has schema = action_schema, prefix = functions, label = type1.

We wish `express_ref:[schema ("." (prefix ".")* label)]` to be replaced by the more generic syntax: `<<express:schema:prefix.label,label>>`. In other words, an Asciidoctor cross-reference, whose textual content (label) is the final string after the dot; and where the first string before a dot (the schema name) is separated from the remainder of the string.

So `express_ref:[action_schema.functions.type1]` will become `<<express:action-schema:functions.type1,type1>>`.

**Comment by opoudjis** [comment]
@w00lf please correct `<<express_ref:` to `<<express:`; that is the expectation behind stepmod2mn counterpart (https://github.com/metanorma/stepmod2mn/issues/2)

**Comment by w00lf** [comment]
> @w00lf please correct `<<express_ref:` to `<<express:`; that is the expectation behind stepmod2mn counterpart ([metanorma/stepmod2mn#2](https://github.com/metanorma/stepmod2mn/issues/2))

Done, pushed to master
