### ISSUE TITLE
Put SVG references in annotations

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod-utils#40]
Express schema descriptions include image maps, in an idiosyncratic Express XML format, based on HTML image maps. Right now they are being output in the conversion code in this repository, as `expg_image` macros. So

https://github.com/metanorma/iso-10303-stepmod/blob/master/data/resources/basic_attribute_schema/basic_attribute_schema_annotated.exp

````
expg_image:basic_attribute_schemaexpg1.xml[]
````

In https://github.com/metanorma/stepmod-utils/issues/38, there is a task to convert those files into SVG files. We want the stylesheet to do so incorporated into the scripts to generate the annotated versions of the express files. 

We also want the expg_image macros to be replaced with image macros inserting those SVG files.

In addition, the source Express XML image maps hyperlink to XML files specific to the various schemas. We want those hyperlinks replaced with cross-references to Express schemas (see https://github.com/metanorma/stepmod-utils/issues/37). And those replacements can only be done when we are compiling the document collection in Metanorma

So to do this, I have created an `svgmap` container as markup in Metanorma: https://github.com/metanorma/metanorma/issues/160. I have not finalised it yet, but you can start implementing this once I have. 

The svgmap container in the context of Express looks like this:

````
[.svgmap]
====
image::basic_attribute_schemaexpg1.svg[]

* <<express:basic_attribute_schema,basic_attribute_schema>>; ../../resources/basic_attribute_schema/basic_attribute_schema.xml
* <<express:support_resource_schema,support_resource_schema>>; ../../resources/support_resource_schema/support_resource_schema.xml
====
````

That is, an Asciidoctor example, with a `[.svgmap]` role attribute, consisting of an image macro nominating the SVG file, and an unordered list, mapping Metanorma references to the HREF value in the source SVG.

`../../resources/basic_attribute_schema/basic_attribute_schema.xml` is what the hyperlink looks like in the source image map; the crossreference before it is what we want to replace it by on Metanorma compilation. I have written code in metanorma to overwrite the hrefs in the SVG file.

Assuming that each image map is pointing to a schema, and not an element within a schema, all we need is a two part internal cross-reference: `<<express:schema_name,schema_name>>`. (The bit after the comma is the display text, which I may end up using as alt text, if SVG supports it. Put it in there just in case.)

If there are any hyperlinks to specific elements, we will need a three-part internal cross-reference, as I document in https://github.com/metanorma/stepmod-utils/issues/37. But I'm pretty sure we will not.

This is a task for @w00lf; I am cc'ing @zakjan, in case he needs to pass information about the list of all schemas to @w00lf.

**Comment by ronaldtse** [comment]
All SVGs have already been generated in metanorma/stepmod2mn#8 for iso-10303-stepmod.

In particular, this is what needs to be done:

1. Change
https://github.com/metanorma/stepmod-utils/blob/b20b7ec042b4882e068a5736a487d4891a1a3538/lib/stepmod/utils/converters/express_g.rb#L7-L14

Example below.

This file:
`data/resource_docs/fundamentals_of_product_description_and_support/resource.xml`

Contains this block:
```xml
      <express-g>
         <imgfile file="basic_attribute_schemaexpg1.xml"/>
         <imgfile file="basic_attribute_schemaexpg2.xml"/>
         <imgfile file="basic_attribute_schemaexpg3.xml"/>
         <imgfile file="basic_attribute_schemaexpg4.xml"/>
         <imgfile file="basic_attribute_schemaexpg5.xml"/>
      </express-g>
```

We need to parse each of these reference files.

The first one `basic_attribute_schemaexpg1.xml` contains this:

```xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../../xsl/res_doc/imgfile.xsl"?>
<!DOCTYPE imgfile.content SYSTEM "../../../dtd/text.ent">
<imgfile.content module="fundamentals_of_product_description_and_support" file="basic_attribute_schemaexpg1.xml">
<img src="basic_attribute_schemaexpg1.gif">
<img.area shape="rect" coords="157,98,305,139" href="../../resources/support_resource_schema/support_resource_schema.xml" />
<img.area shape="rect" coords="10,10,143,51" href="../../resources/basic_attribute_schema/basic_attribute_schema.xml" />
</img>
</imgfile.content>
```

This content refers to:
* an image file `basic_attribute_schemaexpg1.gif`. This is replaced with the new image `basic_attribute_schemaexpg1.svg` in `svgmap`.
* multiple image "shapes", i.e. `<img.area shape ...>` that link to some schema path. This gives you the information needed in `svgmap` of the pattern `<<{anchor},{schema name}>>;{svg href}`:
  * the schema name (`support_resource_schema.support_resource_schema`). `{anchor}` is `express:support_resource_schema `, and `{schema name}` is `support_resource_schema`
  * the "path" which is now an `href` inside the generated SVG. `{svg href}` is `../../resources/support_resource_schema/support_resource_schema.xml`.

With these two types of content we can create the `svgmap` snippet.

```
[.svgmap]
====
image::basic_attribute_schemaexpg1.svg[]

* <<express:support_resource_schema,support_resource_schema>>; ../../resources/support_resource_schema/support_resource_schema.xml
* <<express:basic_attribute_schema,basic_attribute_schema>>; ../../resources/basic_attribute_schema/basic_attribute_schema.xml
====
```
