### ISSUE TITLE
Support <schema_diag> tag

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#41]
We need to convert this also. From metanorma/iso-10303-stepmod#6 .

Missing rendering of `<schema_diag>` image:

> <img width="855" alt="Screen Shot 2021-02-04 at 12 40 23 PM" src="https://user-images.githubusercontent.com/11865/106845577-2be6f680-66e6-11eb-91e5-226d9314646c.png">

**Comment by ronaldtse** [comment]
From iso-10303-stepmod I was only able to find this relevant snippet:

```xml
      <xsl:when test="contains(@file,'schema_diag')">
        
            <xsl:value-of 
              select="concat('Figure 1 ', 
                      ' &#8212; The relationship of schemas of this part to the standard ISO 10303 integration architecture')" />
      </xsl:when>
      <xsl:when test="contains(@file,'schemaexpg')">       
            <xsl:value-of 
              select="concat('Figure D. ', 
                      ' &#8212; Place calculated title here')" />
            </xsl:when>
```

I think we just treat it as a normal `svgmap`.

**Comment by ronaldtse** [comment]
Implemented by @w00lf. Thanks!

**Comment by ronaldtse** [comment]
@w00lf in the latest version we're still seeing this. Can you have a look?

<img width="851" alt="Screenshot 2021-02-25 at 11 50 29 AM" src="https://user-images.githubusercontent.com/11865/109100358-a9d77400-775f-11eb-999c-050a3af09bcb.png">

**Comment by w00lf** [comment]
> @w00lf in the latest version we're still seeing this. Can you have a look?
> 
> <img alt="Screenshot 2021-02-25 at 11 50 29 AM" width="851" src="https://user-images.githubusercontent.com/11865/109100358-a9d77400-775f-11eb-999c-050a3af09bcb.png">

As it turns out this diagram was manually put into the adoc file.

**Comment by ronaldtse** [comment]
Yes this is now fixed in the latest generated version (directly using image::, not svg)
