### ISSUE TITLE
Handle `<eqn>` elements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#46]
From https://github.com/metanorma/iso-10303-stepmod/pull/15#discussion_r578455102

```
<eqn id="eqn2"> <b><i>V</i></b> - (2 - G<sup><i>e</i></sup>) = 0 &#x2003; (2) &#x2003;  
```

**Comment by ronaldtse** [comment]
This element needs to be converted into a stem block:

```
[stem]
++++
...
++++
```

And the inside needs to be parsed by this method:
https://github.com/glossarist/iev-data/blob/45c45971902d88aaddc1e602e94f5de9173fae60/lib/iev/termbase/term_builder.rb#L184

@w00lf can you copy out this method (and related methods) to this gem for this purpose?

Thanks!

**Comment by w00lf** [comment]
> https://github.com/glossarist/iev-data/blob/45c45971902d88aaddc1e602e94f5de9173fae60/lib/iev/termbase/term_builder.rb#L184

Sure, will do, thanks!

**Comment by ronaldtse** [comment]
Thanks @w00lf !

**Comment by w00lf** [comment]
@ronaldtse quick question. I have implemented eqn tag handle as you described, but I am not sure that I am 100% correct. Currently, I handle all nested tags in eqn with reverse_adoc and then prase the result with the code snippet from iev-data, is it correct or do I need to parse tag content with iev-data snippet without nested tags handle by revere_adoc?

**Comment by ronaldtse** [comment]
For `<eqn>` elements there are still some issues:

original:
```xml
<eqn> <b>s</b>(u,v) = (1 - u -v)<sup>3</sup><b>P<sub>1</sub></b> + u<sup>3</sup><b>P<sub>2</sub></b> + v<sup>3</sup><b>P<sub>3</sub></b> + 3(1 - u -v)<sup>2</sup>u<b>P<sub>4</sub></b> + 3(1 - u -v)u<sup>2</sup><b>P<sub>5</sub></b> + 3u<sup>2</sup>v<b>P<sub>6</sub></b> + 3uv<sup>2</sup><b>P<sub>7</sub></b> + 3(1 - u -v)v<sup>2</sup><b>P<sub>8</sub></b> + 3(1 - u -v)<sup>2</sup>v<b>P<sub>9</sub></b> + 6uv(1 - u -v)<b>P<sub>10</sub></b> </eqn>
```

becomes this, which is wrong:
```adoc
[stem]
++++
s(u,v) = (1 - u -v)3P1 + u3P2 + v3P3 + 3(1 - u -v)2uP4 + 3(1 - u -v)u2P5 + 3u2vP6 + 3uv2P7 + 3(1 - u -v)v2P8 + 3(1 - u -v)2vP9 + 6uv(1 - u -v)P10
++++
```

`<sup>3</sup>` means subscript 3, so `(1 - u -v)<sup>3</sup>` should be `(1 - u -v)^{3}`.

Also, `<b>P<sub>4</sub></b>` should be `P_{4}`.
