### ISSUE TITLE
Simplified <<express>> references

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#47]
We're changing from:
```
<<express:managed_model_based_3d_engineering_bom:managed_model_based_3d_engineering_bom.PercentagePly.volumePercent,volumePercent>>
```

to
```
<<express:managed_model_based_3d_engineering_bom.PercentagePly.volumePercent,volumePercent>>
```

Right?

Ping @opoudjis @w00lf

**Comment by ronaldtse** [comment]
@w00lf the original reference:

<<express:managed_model_based_3d_engineering_bom:managed_model_based_3d_engineering_bom.PercentagePly.volumePercent,volumePercent>>

Is too long. We would like to use the new shorter syntax that you implemented, such as <<express: managed_model_based_3d_engineering_bom.PercentagePly.volumePercent>> .

Right?

**Comment by opoudjis** [comment]
Yes, we are using this, and @Intelligent2013 has implemented it too. I thought I had requested it of @w00lf and tandem, but yes, it is needed.
