### ISSUE TITLE
Convert XML comments to ADoc comments

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#51]
https://github.com/metanorma/iso-10303-stepmod/pull/15#discussion_r578463153

> We need to find a way to comment out the "commented code". Nokogiri supports reading commented XML nodes.

```xml
<!-- my
comments
 -->
```

To:
```adoc
// my
// comments
```

**Comment by w00lf** [comment]
> [metanorma/iso-10303-stepmod#15 (comment)](https://github.com/metanorma/iso-10303-stepmod/pull/15#discussion_r578463153)
> 
> > We need to find a way to comment out the "commented code". Nokogiri supports reading commented XML nodes.
> 
> ```
> 
> ```
> 
> To:
> 
> ```
> // my
> // comments
> ```

This is already supported: https://github.com/metanorma/iso-10303-stepmod/pull/15#discussion_r579792152

**Comment by ronaldtse** [comment]
Nice stuff. Thanks!
