### ISSUE TITLE
Auto-release of gem

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#60]
From @CAMOBAP :
> How do you feel about such workflow https://github.com/metanorma/stepmod-utils/blob/master/.github/workflows/release.yml ? Is it makes sense for you?

Yes I think it's good.

Originally from https://github.com/metanorma/iso-10303-stepmod/issues/8#issuecomment-785821797

**Comment by CAMOBAP** [comment]
@ronaldtse is there a condition when we can do autorelease?

At the moment 2 cases covered:
1. after push the version tag to the repo, gem will be pushed to rubygems automatically
2. you can do release with "Run workflow" button on https://github.com/metanorma/stepmod-utils/actions/workflows/release.yml, where you can specify the next version, or strategy how version should be incremented

**Comment by ronaldtse** [comment]
> after push the version tag to the repo, gem will be pushed to rubygems automatically

This is good, right?

**Comment by CAMOBAP** [comment]
@ronaldtse I think so, but sometimes is also good to be able to push gem just with UI, like this:

<img width="1446" alt="Screen Shot 2021-02-25 at 8 43 42 PM" src="https://user-images.githubusercontent.com/2169738/109194252-4aeb1c80-77aa-11eb-8b1f-e34cf7161921.png">

So I propose to keep both)

**Comment by ronaldtse** [comment]
Agree, thanks!
