### ISSUE TITLE
Handle *) in embedded remark content

### ISSUE THREAD

**Issue by zakjan** [metanorma/stepmod-utils#62]
In the latest iso-10303-stepmod master, these files contain `*)` sequence, causing Expressir parser to throw a parse error.

data/modules/generic_expression/arm_annotated.exp - line 290
data/modules/layered_interconnect_module_design/arm_annotated.exp - line 1566
data/resources/geometry_schema/geometry_schema_annotated.exp - line 5308
data/resources/product_data_quality_criteria_schema/product_data_quality_criteria_schema_annotated.exp - line 217
data/resources/product_definition_schema/product_definition_schema_annotated.exp - line 952
data/resources/topology_schema/topology_schema_annotated.exp - line 1969

It's always a bold text inside parentheses:

```
(*"product_definition_schema.product_definition_formation.ur:UR1"
... (through their attribute *of_product*).
*)
```

However, Express spec doesn't support any escape syntax for this sequence.

![Screen Shot 2021-02-28 at 13 19 55](https://user-images.githubusercontent.com/173585/109418468-d04c1800-79c8-11eb-85b5-f4982566e379.png)

Any ideas? How about to insert a zero-width space (\u200B)?

**Comment by ronaldtse** [comment]
@zakjan Just looking at the grammar, does this mean that EXPRESS syntax does not even allow non-ASCII symbols, e.g. unicode, in the remarks?

**Comment by ronaldtse** [comment]
Using AsciiDoc syntax we can do this:
```
(*"product_definition_schema.product_definition_formation.ur:UR1"
... (through their attribute *of_product*{blank}).
*)
```

**Comment by zakjan** [comment]
Good catch, there are no UTF-8 chars or spaces in the spec. They are supported in Expressir because I simplified these rules to "anything except `*)`" (or "anything except `\n`" for tail remarks) already from the first implementation. https://github.com/lutaml/express-grammar/blob/master/Express.g4#L1129-L1137

I referred to the spec to show that there is no official escape sequence. Anything that splits `*` and `(` / `)` should fix this issue.

**Comment by ronaldtse** [comment]
@zakjan thanks for the confirmation. This also means that diacritics are also disallowed. Let me file a separate issue in Expressir describing this problem to see advice from ISO/TC 184/SC 4/WG 12.

**Comment by ronaldtse** [comment]
Let's address the current issue by making this modification:

If a bolded statement (`<b>`):
* starts immediately after a `(` character, or
* ends immediately before a `)` character

We insert the `{blank}` between them in converting.

Does this sound reasonable @zakjan @w00lf ? (This also needs to be addressed by @Intelligent2013 )

**Comment by zakjan** [comment]
Yes.

**Comment by w00lf** [comment]
> Let's address the current issue by making this modification:
> 
> If a bolded statement (`<b>`):
> 
> * starts immediately after a `(` character, or
> * ends immediately before a `)` character
> 
> We insert the `{blank}` between them in converting.
> 
> Does this sound reasonable @zakjan @w00lf ? (This also needs to be addressed by @Intelligent2013 for stepmod2mn, which needs a separate ticket)

Created hotfix PR - #63

**Comment by ronaldtse** [comment]
The PR from @w00lf works. Closing.
