### ISSUE TITLE
cannot load such file -- win32/file - windows GA

### ISSUE THREAD

**Issue by w00lf** [metanorma/stepmod-utils#87]
Failing specs with this error, example - https://github.com/metanorma/stepmod-utils/pull/85/checks?check_run_id=2638563362. @CAMOBAP can you help here?

**Comment by w00lf** [comment]
https://github.com/metanorma/stepmod-utils/pull/85

**Comment by CAMOBAP** [comment]
reported https://github.com/djberg96/ptools/issues/42

PR: https://github.com/metanorma/stepmod-utils/pull/88 - temporal workaround

**Comment by w00lf** [comment]
> #88

Thx, @CAMOBAP

**Comment by ronaldtse** [comment]
@CAMOBAP @w00lf In order to merge it I've refactored the bit so that the `File.which` call doesn't get executed in specs (if the directory is not a CVS repo). I will also merge #88. Thanks!

**Comment by CAMOBAP** [comment]
@w00lf @ronaldtse BTW https://rubygems.org/gems/ptools/versions/1.4.2-universal-mingw32 so we can revert the original change

**Comment by ronaldtse** [comment]
@CAMOBAP your 3d72d26 somehow got rid the whole line, we needed to keep the ptools line, so it's returned in 2e871bb. So this is all done. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse AFAIR we have it as transitive dependency, isn't it?

**Comment by ronaldtse** [comment]
@CAMOBAP no, it's used here:
https://github.com/metanorma/stepmod-utils/blob/3001849651ea07e7950495d87998420ca353be09/lib/stepmod/utils/terms_extractor.rb#L60

**Comment by CAMOBAP** [comment]
@ronaldtse my bad, thanks for making attention to this
I just reverted my original commit and looks like  there was no dependence on 'ptools' before
