### ISSUE TITLE
Move terms/definitions processing to new Glossarist gem

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#90]
Thanks to @skalee we are standardising all concept handling in the newly released Glossarist gem.

This issue is to perform the refactor in stepmod-utils to utilize the glossarist gem, just like how it was done in the IEC iev-data gem:
https://github.com/glossarist/iev-data/pull/189

**Comment by ronaldtse** [comment]
This task is related to, but not dependent on, or is a dependency of #86

**Comment by w00lf** [comment]
@ronaldtse implemented in https://github.com/metanorma/stepmod-utils/pull/94

**Comment by w00lf** [comment]
@ronaldtse can we close this one?

**Comment by ronaldtse** [comment]
Not perfect but not critical for now.
