### ISSUE TITLE
Bolded terms next to each other loses whitespace in between

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#93]
e.g.:
```
A *profile_floor* is a type of *shape_aspect* that is the representation
of the bottom condition for an *outside_profile**feature_definition*.
```

Notice that `*outside_profile*` and `*feature_definition*` should have a space in between.

**Comment by ronaldtse** [comment]
@w00lf this is from stepmod-utils, on this file:

https://github.com/metanorma/iso-10303-stepmod-cvs/blob/7e7e7e3a83401cc5b4b676e4083cc9f13b04a9c3/resources/aic_machining_feature/descriptions.xml#L6195-L6200

**Comment by w00lf** [comment]
> @w00lf this is from stepmod-utils, on this file:
> 
> https://github.com/metanorma/iso-10303-stepmod-cvs/blob/7e7e7e3a83401cc5b4b676e4083cc9f13b04a9c3/resources/aic_machining_feature/descriptions.xml#L6195-L6200

Thanks, the issue was with Stepmod::Utils::StepmodDefinitionConverter, it uses a separate converter for `express_ref`, fixed in https://github.com/metanorma/stepmod-utils/pull/95
