### ISSUE TITLE
stepmod-terms-extract should filter out `status="withdrawn"` entries

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#96]
From @TRThurman :

> There is an attribute '@status' that should be used to filter repository_index.xml contents
> * If a resource is "withdrawn" the resource is to be ignored.
> * If a resource_doc is "withdrawn" the resource_doc is to be ignored.

There are also `<module>` elements that are marked with `status="withdrawn"`.

In the following code we should omit the entries if they have this status.

Code to change:
https://github.com/metanorma/stepmod-utils/blob/ef9bc1677c195cb5b56ea780122afeee6fc11025/lib/stepmod/utils/terms_extractor.rb#L76-L102

**Comment by w00lf** [comment]
@ronaldtse implemented in https://github.com/metanorma/stepmod-utils/pull/99
